name: CI

on: [push]

jobs:
  test:
    name: Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14, 16]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: npm install
        run: npm ci

      - name: Set up Google auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run tests
        run: npm test
